### PR TITLE
wrapInTransaction infer to the original function

### PR DESCRIPTION
**Pull request by lytc**

### CODE REVIEW

**Comment by Aliheym** [comment]
Hi, thanks for your PR. Maybe it will be better to add infer for function arguments too?

**Comment by lytc** [comment]
@Aliheym It already does!
Untitled

**Comment by Aliheym** [comment]
> @Aliheym It already does!
> Untitled
> 

Cool, thanks

**Comment by lytc** [comment]
@Aliheym Thank you so much for approved the PR. Could you also help release this fix as well?

**Comment by Aliheym** [comment]
@lytc done.

**Pull request merged**
