### PR TITLE
patch repository prototype and the prototype extend method

### PR DESCRIPTION
**Pull request by mekh**
This patch allows using either dataSource.getRepository().extend() or custom repositories:
```
@Injectable()
export class CustomRepository extends Repository<Entity> {
  constructor(private readonly dataSource: DataSource) {
    super(Entity, dataSource.manager);
  }

  async customMethod() {}
}
```

```
export const customRepository = dataSource.getRepository(Entity)
    .extend({
      async customMethod(): Promise<any> {
          ...
      },
    });
```

### CODE REVIEW

**Comment by Aliheym** [comment]
Hi, thanks for good PR. Do you want to support custom repositories classes from the TypeORM v0.2?

**Comment by mekh** [comment]
Hi,
I'm maintaining a project that uses **typeorm** v0.3.7, **@nestjs/typeorm** v9.0.1 and custom repositories built using this: [CustomRepository for typeorm@0.3.x](https://gist.github.com/anchan828/9e569f076e7bc18daf21c652f7c3d012)

It would be great to have your module support this approach.

**Comment by AmoOAO** [comment]
This is working for me !!! PLS review & merge it !

**Comment by lukeurban** [comment]
Doesn't work :(

**Comment by Aliheym** [comment]
Sorry for such delay. I've just released this feature. 

@mekh thank you for your PR.

**Pull request merged**
